/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import MetodoSQL.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

//Autor libre

public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtdatos = new javax.swing.JTable();
        btn_cargar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("PRODUCTOS QUE SE ENCUENTRAN EN LA EMPRESA");

        Jtdatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo barras", "Nombre producto", "cantidad", "Valor"
            }
        ));
        Jtdatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtdatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Jtdatos);

        btn_cargar.setText("cargar");
        btn_cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarActionPerformed(evt);
            }
        });

        btn_regresar.setText("regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(btn_cargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_regresar)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cargar)
                    .addComponent(btn_regresar))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        Interfaz_agregar_producto ob = new Interfaz_agregar_producto();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarActionPerformed
    try {
            DefaultTableModel modelo = new  DefaultTableModel();//creo un modelo basico por el Jtable
            Jtdatos.setModel(modelo);//mi variable que le puse a mi Jtablet y la seteo en lo que hay en modelo
            PreparedStatement sentencia_preparada = null;//llamo la libreria y le pongo el nombre y la igualo a nulo/Libreria necesaria para la ejecuccion
            ResultSet resultado = null;  //tambien el ResultSet el nombre y se iguala a nulo
            ConexionBD conexion = ConexionBD.getInstance();//creo un objeto a mi clase de ConexionBD
            Connection con = conexion.getConnection();//Llamo la libreria y le pongo un nombre, esto la igual con la conexion establecida directamente
            String consulta = "SELECT * FROM tipo_producto";
            //hago una consulta de tipo String y alli va la consulta necesaria
            sentencia_preparada = con.prepareStatement(consulta);
            //sentencia preparada va hacer igual a la conexion.sintaxis para que haga la consulta y dentro de sus parametros va la sintaxis necesaria
            resultado = sentencia_preparada.executeQuery();
            //resultado que es mi ResultSet va hacer igual a lo que me hizo mi sentencia preparada o variable .funcion
            ResultSetMetaData rsmd = resultado.getMetaData();
            //llamo una libreria ResultSetMetaData y le pongo un nombre y eso va hacer igual a resultado y esto es pasandole el resultado de la consulta
            int cantidad_colum = rsmd.getColumnCount();
            //creo una variable y alli mi rsmd o variable . funcion de que me diga cuantas columnas hay en la base de datos o gp2013
            modelo.addColumn("Cod_barra");
            //los datos que hay y que se va reflejar lo que traigamos de BD en campos individuales
            modelo.addColumn("nombre_producto");
            modelo.addColumn("cantidad");
            modelo.addColumn("valor");
            while(resultado.next()){//el while es para ir recorriendo los datos de la consulta
                Object [] filas = new Object[cantidad_colum];//creo un array con la cantidad de columnas que hicimos hace poco
                for(int i=0;i<filas.length;i++){//el for es para ir pasando todos los datos a este tipo Objeto 
                    filas[i] = resultado.getObject(i+1);//esto es para que diga la columna de la BD
                }
                modelo.addRow(filas);//relleno filas por medio del array que creamos
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_cargarActionPerformed

    private void JtdatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtdatosMouseClicked
        int seleccionar = Jtdatos.rowAtPoint(evt.getPoint());
        String cod_barras = String.valueOf(Jtdatos.getValueAt(seleccionar, 0));
        String nombre_producto = String.valueOf(Jtdatos.getValueAt(seleccionar, 1));
        String cantidad = String.valueOf(Jtdatos.getValueAt(seleccionar, 2));
        String valor = String.valueOf(Jtdatos.getValueAt(seleccionar, 3));
        this.dispose();
        Interfaz_agregar_producto ob = new Interfaz_agregar_producto();
        ob.txt_cod_barras.setText(cod_barras);
        ob.txt_producto.setText(nombre_producto);
        ob.txt_cantidad_producto.setText(cantidad);
        ob.txt_valor_producto.setText(valor);
        ob.setVisible(true);
    }//GEN-LAST:event_JtdatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jtdatos;
    private javax.swing.JButton btn_cargar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
