/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresa;

import java.awt.Color;
import javax.swing.border.LineBorder;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        btn_generar_venta = new javax.swing.JButton();
        btn_agregar_producto = new javax.swing.JButton();
        btn_agregar_documento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interfaz principal");
        setPreferredSize(new java.awt.Dimension(800, 368));
        setResizable(false);

        Titulo.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("INTERFAZ PRINCIPAL DE LA EMPRESA");

        btn_generar_venta.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        btn_generar_venta.setText("Generar venta");
        btn_generar_venta.setContentAreaFilled(false);
        btn_generar_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_generar_ventaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_generar_ventaMouseExited(evt);
            }
        });
        btn_generar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generar_ventaActionPerformed(evt);
            }
        });

        btn_agregar_producto.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        btn_agregar_producto.setText("Agregar producto");
        btn_agregar_producto.setContentAreaFilled(false);
        btn_agregar_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregar_productoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregar_productoMouseExited(evt);
            }
        });
        btn_agregar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_productoActionPerformed(evt);
            }
        });

        btn_agregar_documento.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        btn_agregar_documento.setText("Agregar documento");
        btn_agregar_documento.setContentAreaFilled(false);
        btn_agregar_documento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregar_documentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregar_documentoMouseExited(evt);
            }
        });
        btn_agregar_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_documentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_generar_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(btn_agregar_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_agregar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_generar_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_agregar_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btn_agregar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generar_ventaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generar_ventaMouseEntered
        btn_generar_venta.setBorder(new LineBorder(Color.GREEN));
    }//GEN-LAST:event_btn_generar_ventaMouseEntered

    private void btn_generar_ventaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generar_ventaMouseExited
        btn_generar_venta.setBorder(null);
    }//GEN-LAST:event_btn_generar_ventaMouseExited

    private void btn_agregar_productoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_productoMouseEntered
        btn_agregar_producto.setBorder(new LineBorder(Color.GREEN));
    }//GEN-LAST:event_btn_agregar_productoMouseEntered

    private void btn_agregar_productoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_productoMouseExited
        btn_agregar_producto.setBorder(null);
    }//GEN-LAST:event_btn_agregar_productoMouseExited

    private void btn_generar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generar_ventaActionPerformed
        this.dispose();
        Interfaz_generar_venta ob = new Interfaz_generar_venta();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_generar_ventaActionPerformed

    private void btn_agregar_documentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_documentoMouseEntered
        btn_agregar_documento.setBorder(new LineBorder(Color.GREEN));
    }//GEN-LAST:event_btn_agregar_documentoMouseEntered

    private void btn_agregar_documentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_documentoMouseExited
        btn_agregar_documento.setBorder(null);
    }//GEN-LAST:event_btn_agregar_documentoMouseExited

    private void btn_agregar_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_documentoActionPerformed
        Interfaz_agregar_documento ob = new Interfaz_agregar_documento();
        ob.setVisible(true);
        ob.limpiarcajas();
        this.dispose();
    }//GEN-LAST:event_btn_agregar_documentoActionPerformed

    private void btn_agregar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_productoActionPerformed
        Interfaz_agregar_producto ob = new Interfaz_agregar_producto();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregar_productoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btn_agregar_documento;
    private javax.swing.JButton btn_agregar_producto;
    private javax.swing.JButton btn_generar_venta;
    // End of variables declaration//GEN-END:variables
}
